SIM:
  INIT_VIEWER_CAMERA_POSITION: [0.6, 0.0, 0.8]
  INIT_VIEWER_CAMERA_TARGET: [0.0, 0.0, 0.0]
ENV:
  # TARGET_POSITION_X
  # TARGET_POSITION_Y
  DISPLAY_TARGET: False
  RANDOM_SEED: 0
  ##### Primitive Objects #####
  # NUM_PRIMITIVE_OBJECTS
  # PRIMITIVE_OBJECT_BASE_POSITION
  PICKED_OBJECT_IDX: 0
  ##### MANO Hand #####
  # MANO_MODEL_FILENAME
  # MANO_POSE_FILENAME
  # MANO_INITIAL_TARGET
  # MANO_INITIAL_BASE
  # MANO_FINAL_TARGET
  # MANO_FINAL_BASE
  ##### Offscreen Rendering #####
  RENDER_OFFSCREEN: True
  RENDER_DIR: 'datasets/pick-and-place'
  NUM_OFFSCREEN_RENDERER_CAMERA: 2
  OFFSCREEN_RENDERER_CAMERA_POSITION: [[0.45, 0.0, 0.6], [0.0, 0.6, 0.45]]
  OFFSCREEN_RENDERER_CAMERA_TARGET: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
